version: '3.8'

services:
  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    # ports:
    #   - 6001:6001
    #   - 8096:8096
    networks:
      - nginx_network
  # web:
  #   image: kingrayhan/hello-docker
    # ports:
    #   - 4000:4000
    # networks:
    #   - nginx_network
  nginx_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./.docker-data/data:/data
      - ./.docker-data/letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network

networks:
  nginx_network: